return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  branch = "main",
  build = ":TSUpdate",
  dependencies = {
    "joerdav/templ.vim",
    "vrischmann/tree-sitter-templ",
  },
  config = function()
    require("nvim-treesitter").setup({})
    require("nvim-treesitter").install({
      "bash",
      "c",
      "cpp",
      "go",
      "lua",
      "python",
      "rust",
      "ruby",
      "tsx",
      "javascript",
      "typescript",
      "vimdoc",
      "vim",
      "terraform",
      "css",
      "html",
      "latex",
      "scss",
      "svelte",
      "vue",
      "typst",
      "regex",
      "markdown",
      "markdown_inline",
      "hcl",
    })
  end,
}
